name: Deploy to S3

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Set your desired AWS region here

    # Step 3: Sync files with S3
    - name: Deploy to S3
      run: |
        aws s3 sync . s3://your-s3-bucket-name --exclude ".git/*" --delete
      env:
        AWS_REGION: us-east-1  # Set your desired AWS region here

    # Step 4: Invalidate CloudFront cache (Optional - if using CloudFront)
    - name: Invalidate CloudFront Cache
      if: success() && github.ref == 'refs/heads/main'
      run: |
        aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
      env:
        AWS_REGION: us-east-1
